import { Header } from '../../components/Header/Header';
import '../../globals.css';

export const metadata = {
  title: 'Welcome to my website!',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
